#:schema node_modules/wrangler/config-schema.json

name = "farmfest"
main = "./server.ts"
workers_dev = true

routes = [
  { pattern = "farmfest.bigbohne.de", custom_domain = true }
]

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./build/client"