#:schema node_modules/wrangler/config-schema.json

name = "farmfest"
main = "./server.ts"
workers_dev = true

routes = [
  { pattern = "shop.example.com", custom_domain = true }
]

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

[assets]
directory = "./build/client"

[build]
command = "npx projen build"